server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&allowMultiQueries=true&useUnicode
    =true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root



elasticjob:
  reg-center:
    server-lists: localhost:2181
    namespace: elasticjob-demo-cf
  jobs:
    cfJob:
      description: 测试
      elasticJobClass: chenfeidemo.elasticjobdemo.job.DemoJob
      cron: 0/5 * * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
#    dataFlowJob:
#      description: 测试-2
#      elasticJobClass: chenfeidemo.elasticjobdemo.job.DemoDataFlowJob
#      cron: 0/5 * * * * ?
#      shardingTotalCount: 3
#      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
#      props:
#        streaming.process: true
  tracing:
    type: RDB

